name: Amazon Ranking Scheduler

on:
  schedule:
    - cron: "0 * * * *"   # 毎時0分に実行
  workflow_dispatch:       # 手動で実行できるボタンも追加

permissions:
  contents: write          # Excelをcommit/pushするために必要

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run amazonranking_matome.py
        run: |
          python amazonranking_matome.py

      - name: Commit and push updated Excel
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add amazonranking_matome.xlsx amazonranking_matome_backup.xlsx || true
          git commit -m "Update ranking data [skip ci]" || echo "No changes to commit"
          git push
